### ISSUE TITLE
How to configure?

### ISSUE THREAD

**Issue by core01** [aduryagin/vscode-jira-worklog#7]
Hi @aduryagin, thank you for the extension.
Could you please, explain how to set it up?

**Comment by aduryagin** [comment]
i don't sure that extension works by now. latest maintenance was 2 years ago) but you can fork and fix extension. you can just try to install and change extension settings in preferences.

**Comment by core01** [comment]
> you can just try to install and change extension settings in preferences

VSCode can't find any settings for the extension, maybe because 2 years have passed.

> i don't sure that extension works by now. latest maintenance was 2 years ago) but you can fork and fix extension.

@aduryagin okay, I will think about it, thank you, I'm sorry if I bothered you.
